# Generated by Django 3.2 on 2021-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('article', models.TextField()),
            ],
        ),
    ]
